### PR TITLE
MERC-1537 1.4.1 cherry pick

### PR DESCRIPTION
**Pull request by mcampa**
This is already reviewed, it is cherry picked from the codefreeze branch

@bc-ong @mattolson

### CODE REVIEW

**Comment by bc-ong** [comment]
:+1:

**Comment by mattolson** [comment]
👍

**Comment by stencil-check** [comment]
Generating bundle for 391e0cd

**Comment by stencil-check** [comment]
Generating bundle for commit c547fd4

**Comment by stencil-check** [comment]
Generating bundle for commit 04d5af2

**Comment by stencil-check** [comment]
Generating bundle for commit dd1a194

**Comment by bc-ranji** [comment]
💚

**Pull request merged**
