### PR TITLE
Updated pace reference

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Please see https://github.com/HubSpot/pace/issues/328#issuecomment-246210165

Without this patch I cannot get a clean build of stencil in [my Docker setup](https://gist.github.com/Lewiscowles1986/d4ef75a2d9c3e7d6e1794c3e90246c9a)

### CODE REVIEW

**Comment by mcampa** [comment]
Don't you need to add this line to the webpack config file? `webpack.conf.js

```
{ test: require.resolve("pace-progress"), loader: "imports?define=>false" }

```

**Comment by RafaelUbaldo** [comment]
Hey, guys. How do we get a fix for this right now to update Stencil themes?

**Comment by dstaley** [comment]
@RafaelUbaldo for the time being, you can update your `package.json` to reference an older version of pace from before the name change:
```
"pace": "hubspot/pace#a03f1f1de62c9cea6c88b2267b8d7a83858b6cb6"
```
If your still getting errors, run `rm -rf node_modules` and then `npm install`. This will make sure Node isn't confused by having both `pace` and `pace-progress` modules.

**Comment by Lewiscowles1986** [comment]
perhaps more activity toward hubspot pace might also help speed this up

**Pull request merged**
