### PR TITLE
Swatch resize

### PR DESCRIPTION
**Pull request by johnhebron**
Ability to change the size of swatches on product pages.

### CODE REVIEW

**Comment by johnhebron** [comment]
@bc-adamferenzi @cristycarpenter @briansilvey

**Comment by johnhebron** [comment]
@mcampa This one is ready to be critiqued. Thank you!

**Comment by mcampa** [comment]
@bc-miko-ademagic please take a 👀  at the sass changes

**Comment by johnhebron** [comment]
@bc-miko-ademagic Let me know if you need anything fixed up :) Thanks!

**Comment by mcampa** [comment]
👍

**Comment by mjschock** [comment]
new PR (#895) opened to re-introduce these changes

**Pull request merged**
