### PR TITLE
Revert "Swatch resize"

### PR DESCRIPTION
**Pull request by mcampa**
Reverts https://github.com/bigcommerce/stencil/pull/855

@bc-ranji @bc-adamferenzi

### CODE REVIEW

**Comment by bc-adamferenzi** [comment]
@johnhebron

**Comment by bc-adamferenzi** [comment]
I don't know the context here @mcampa so I'll defer to John if there are any questions/concerns.

**Comment by mcampa** [comment]
@johnhebron

**Comment by aleachjr** [comment]
👍

**Pull request merged**
