### PR TITLE
CHECKOUT-1308: re-position optimized checkout settings 

### PR DESCRIPTION
**Pull request by jordanwink201**
re-position optimized checkout settings to better match public docs

### Testing

https://store-sdu38plspr.my-integration.zone/

@bigcommerce/checkout @mcampa @bc-mkatz @lord2800

### CODE REVIEW

**Comment by aleachjr** [comment]
This prob needs to be reverted and put into a feature branch as we are in code freeze and no merges to master until December.

**Comment by jordanwink201** [comment]
@aleachjr :+1: sorry about that, was trying to get it into the stencil repo before we release Cornerstone 1.4.0 on Monday. Will be reverted.

**Comment by aleachjr** [comment]
If there is already an exception to get this out then it should stay. I know there was talk this week trying to get it out but wasnt sure that it was happening. If you know it is happening then lets leave it for Monday.

**Comment by bc-mkatz** [comment]
I'm the one who should apologize for the confusion. I requested this for after code freeze. Please just do what works.

**Pull request merged**
