### PR TITLE
MERC-111 - Fix text cutoff in search dropdown

### PR DESCRIPTION
**Pull request by mickr**
MERC-111 - Fix text cutoff in search dropdown

* Unset height rule for the dropdown search bar, the results with going with the default height instead of being explicitly sized.

### CODE REVIEW

**Comment by mickr** [comment]
Before using Firefox
screen shot 2016-03-21 at 3 16 49 pm

After using Firefox
screen shot 2016-03-21 at 3 17 06 pm

@bc-chris-roper @bc-miko-ademagic

**Comment by hegrec** [comment]
:+1:

**Comment by indominus** [comment]
I'm cool with this, but make sure that it's tested in all major browsers including IE. I have a feeling that it would've obviously been set for a reason, and typically form elements are annoying little dudes cross-browser. One of the browsers might need an explicit height set.

**Comment by mickr** [comment]
I tested on Chrome, Safari, and Firefox... I don't currently have IE but maybe @bc-arun can test?

**Comment by bc-chris-roper** [comment]
What that issue looks like based on the screenshot isn't that the height is the problem on its own, but that the specified height combined with the font-size and padding of the box doesn't leave enough space for the text.

So another approach to fix it would be to just increase the height to what it ideally should be.

**Comment by bc-arun** [comment]
@mickr I verified it on IE 13 & 12. Looks good.
screen shot 2016-03-22 at 10 14 19 am

**Comment by mickr** [comment]
@bc-arun can you give this the green heart?

**Comment by bc-arun** [comment]
:green_heart:

**Pull request merged**
