### PR TITLE
Added Quickview toggle to theme editor via change to schema file

### PR DESCRIPTION
**Pull request by bc-adamferenzi**
Added quickview toggle
https://jira.bigcommerce.com/browse/MERC-1230

### CODE REVIEW

**Comment by bookernath** [comment]
Hey Adam, I just realized we duplicated efforts here. I put in a PR against MERC-558:

https://github.com/bigcommerce/stencil/pull/860

One critique of this PR:

There's already a property covering quick view in the config.json. Yours will either 1) be ignored or 2) override - and you've actually changed the default behavior in yours to HIDE quick view. Is this intended?

**Comment by bc-adamferenzi** [comment]
@bookernath thanks, I don't know how I missed that existing mention in config.json, I swear I had searched!  I shouldn't do this stuff when I'm tired.  I can adjust the PR pretty easily, or do you already have it covered?

**Comment by bc-adamferenzi** [comment]
@mcampa if you have a chance to review

**Comment by bookernath** [comment]
Just to close the loop, I closed my PR in favor of this one.

**Pull request merged**
